### ISSUE TITLE
Mod Downloader cant find any games

### ISSUE THREAD

**Issue by tppsch** [amakvana/SwitchEmuModDownloader#43]
Hey

I copied the .exe file into the yuzu.exe folder and after I click on "Download Game Mods" it downloads mods for 0 games. 
However, my games are listed in the emu.
One of the games is e.g. Mario Wonder with the same ID that can be found in the repo of theboy181.

**Comment by amakvana** [comment]
Hey! 

Can you post the games titles, versions and their ID's you're trying to pull mods for?

In addition to this, can you zip and upload your `qt-config.ini` file here too for me to have a look at  

Cheers

**Comment by darkhyper24** [comment]
how about Demon Slayer - Kimetsu no Yaiba it has the same problem

**Comment by amakvana** [comment]
> how about Demon Slayer - Kimetsu no Yaiba it has the same problem

@darkhyper24 - as this is a different title to the OP's, please can you open another Issue and fill out the requested form

Thanks

**Comment by ghost** [comment]
> Hey!
> 
> Can you post the games titles, versions and their ID's you're trying to pull mods for?
> 
> In addition to this, can you zip and upload your `qt-config.ini` file here too for me to have a look at.
> 
> For your example, theboy181's server hosts Super Mario Wonder mods for v1.0.0, if your game copy is anything else, the mods won't pull as the versions do not match.
> 
> Cheers

Hey,

the Gameversion is 1.0.0 whith the id 010015100B514000

[qt-config.zip](https://github.com/amakvana/SwitchEmuModDownloader/files/14546869/qt-config.zip)

**Comment by amakvana** [comment]
Thanks for that, it looks like it's due to a naming convention on the authors repo. As the version number is stored as "v1.0.0" instead of "1.0.0", it doesn't match due to the character "v".

I will open up an Issue on their GitHub requesting an edit of the version naming convention.

Cheers! 

EDIT: Issue has been opened 

https://github.com/theboy181/switch-ptchtxt-mods/issues/47

**Comment by GMStu** [comment]
Wanted to add to this issue. Using Batocera and had to SSH into that computer ( _DISPLAY=:0 ./SwitchEmuModDownloader_)

It downloads the game mods but times out after 100 seconds trying to "Scanning games library" - it stays at 0%
Nothing appears on the properties of any of the games in my hard drive


> Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage, Boolean, Boolean, CancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage, Boolean, CancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage, Boolean, CancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage, CancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception, Boolean, HttpResponseMessage, CancellationTokenSource, CancellationToken, CancellationTokenSource)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage, CancellationToken)
   at SwitchEmuModDownloader.Classes.Downloaders.OfficialSwitchModDownloader.DownloadHtmlDocumentAsync()
   at SwitchEmuModDownloader.Classes.Downloaders.OfficialSwitchModDownloader.ReadGameTitlesDatabaseAsync()
   at SwitchEmuModDownloader.MainWindow.BtnDownload_ClickAsync(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.X11.X11PlatformThreading.CheckSignaled()
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at SwitchEmuModDownloader.Program.Main(String[])
Aborted
[root@BATOCERA /userdata/system/configs/yuzu]# 
——————————————————————————

**Comment by amakvana** [comment]
> Wanted to add to this issue. Using Batocera and had to SSH into that computer ( _DISPLAY=:0 ./SwitchEmuModDownloader_)
> 
> It downloads the game mods but times out after 100 seconds trying to "Scanning games library" - it stays at 0% Nothing appears on the properties of any of the games in my hard drive
> 

I've been notified that the "Official Switch-Mods Repo" is currently down. I'm going to release an update shortly fixing this.

In the meantime, select another repo and try again.

**Comment by TOTKSWITCHPIRATE** [comment]
bro i need help i have the same problem it just says this 
![Screenshot 2024-05-03 175021](https://github.com/amakvana/SwitchEmuModDownloader/assets/168754651/9eec8701-ba84-4f1e-9d09-40d6ea37cd14)
